### ISSUE TITLE
Attempting to use an unsafe value in a safe context.

### ISSUE THREAD

**Issue by DinisCruz** [angular-ui/ui-select#1062]
I was trying to use ui-select and am hitting on this error

```
Error: [$sce:unsafe] Attempting to use an unsafe value in a safe context.
http://errors.angularjs.org/1.4.1/$sce/unsafe
  at REGEX_STRING_REGEXP (http://localhost:12345/angular/js/lib.js:68:12)
  at htmlSanitizer (http://localhost:12345/angular/js/lib.js:16511:13)
  at getTrusted (http://localhost:12345/angular/js/lib.js:16675:16)
  at Object.$get.sce.(anonymous function) [as getTrustedHtml] (http://localhost:12345/angular/js/lib.js:17355:16)
  at Object.ngBindHtmlWatchAction (http://localhost:12345/angular/js/lib.js:22232:29)
  at Object.scopePrototype.$watch.arguments.(anonymous function) [as fn] (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1874:36)
  at Scope.$get.Scope.$digest (http://localhost:12345/angular/js/lib.js:15667:29)
  at Scope.scopePrototype.$digest (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1893:23)
  at Scope.$get.Scope.$apply (http://localhost:12345/angular/js/lib.js:15935:24)
  at Scope.scopePrototype.$apply (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1956:22)
  at HTMLInputElement.<anonymous> (http://localhost:12345/angular/js/lib.js:23244:23)
  at HTMLInputElement.eventHandler (http://localhost:12345/angular/js/lib.js:3264:21)
```

I'm using jade instead of html (which for reference is here)

```jade
block content
    div(ng-controller="Select_Controller")
        h3 Selectize theme
        p Selected: {{country.selected}}
        ui-select(ng-model="country.selected" theme="selectize" ng-disabled="disabled" style="width: 300px;" title="Choose a country")
            ui-select-match(placeholder="Select or search a country in the list...") {{$select.selected.name}}
            ui-select-choices(repeat="country in countries | filter: $select.search")
                span(ng-bind-html="country.name | highlight: $select.search")
                small(ng-bind-html="country.code | highlight: $select.search")

        link(rel="stylesheet" href="/angular/css/lib.css")
        script(src='/angular/js/lib.js')
        script(src='/angular/js/code.js')
        script.
            angular.bootstrap(document, ["App"])
```

Any ideas on where could be the prob?

**Comment by IVLMediaInc** [comment]
Having same issue here. I had used angular-ui-select in a previous project with no errors, but it seems the plugin is not working with newer versions of angular.

**Comment by brunopaz** [comment]
Try to add ngSanitize dependency. It worked for me using angular 1.4+

**Comment by ChristianLJ** [comment]
ngSanitize also seems to solve the problem for me using Angular 1.4.5.

**Comment by MtDalPizzol** [comment]
Same problem here, but I already have included ngSanitize. =/

**Comment by wesleycho** [comment]
Please post a reproduction in Plunker.

**Comment by TravisTam** [comment]
it works. thinks

**Comment by akoskm** [comment]
adding ngSanitize solves this in angular 1.3.15.
