### ISSUE TITLE
checking length on undefined.

### ISSUE THREAD

**Issue by gshireesh** [angular-ui/ui-select#1105]
at
   ctrl.getPlaceholder = function(){
        //Refactor single?
        if($select.selected.length) return;  
       // code suggested here  if($select.selected && $select.selected.length) RETURN;
        return $select.placeholder;
      };

angular.js:12330 TypeError: Cannot read property 'length' of undefined
    at uis.directive.controller.ctrl.getPlaceholder (http://localhost:3000/vendor/js/select.js:1148:28)
    at fn (eval at <anonymous> (http://localhost:3000/vendor/js/angular.js:13145:15), <anonymous>:2:285)
    at Object.expressionInputWatch [as get] (http://localhost:3000/vendor/js/angular.js:14127:31)
    at Scope.$get.Scope.$digest (http://localhost:3000/vendor/js/angular.js:15675:40)
    at Scope.$get.Scope.$apply (http://localhost:3000/vendor/js/angular.js:15951:24)
    at HTMLDivElement.<anonymous> (http://localhost:3000/vendor/js/angular.js:23303:23)
    at HTMLDivElement.jQuery.each.jQuery.event.special.(anonymous function).handle (http://localhost:3000/vendor/js/jquery.js:4765:29)
    at HTMLDivElement.jQuery.event.dispatch (http://localhost:3000/vendor/js/jquery.js:4435:9)
    at HTMLDivElement.jQuery.event.add.elemData.handle (http://localhost:3000/vendor/js/jquery.js:4121:28)

**Comment by arikfr** [comment]
Fixed in #1115.

**Comment by dimirc** [comment]
https://github.com/angular-ui/ui-select/pull/1115 merged

**Comment by danielwegener** [comment]
Any chance to get this fix released soon? :)
