### ISSUE TITLE
Does not work with latest angular 1.5.0-build...

### ISSUE THREAD

**Issue by NathanWalker** [angular-ui/ui-select#1239]
```
Error: [ui.select:transcluded] http://errors.angularjs.org/1.5.0-build.4310+sha.0c8a9a0/ui.select/transcluded?p0=Expected%201%20.ui-select-match%20but%20got%20'%7B0%7D'.&p1=0
    at ...ommitted...
    at http://localhost:8000/scripts/support/uiselect.js:968:19
    at ...ommitted...
    at ...ommitted...
    at ...ommitted...
    at p (...ommitted...)
    at uis.directive.$timeout.compile (http://localhost:8000/scripts/support/uiselect.js:956:9)
    at ca (...ommitted...)
    at L (...ommitted...)
    at ...ommitted... <div class="ui-select-container ui-select-bootstrap dropdown" ng-class="{open: $select.open}" ng-model="foundItem.selected" theme="bootstrap" reset-search-input="false" on-select="selectedSearch($item, $model)" style="width: 80%">(anonymous function) @ ...ommitted...(anonymous function) @ ...ommitted...:86(anonymous function) @ ...ommitted...:10616ca @ ...ommitted...:79L @ ...ommitted...:67(anonymous function) @ ...ommitted...:74(anonymous function) @ ...ommitted...:124n.$eval @ ...ommitted...:139n.$digest @ ...ommitted...:136n.$apply @ ...ommitted...:139(anonymous function) @ ...ommitted...:4490n.event.dispatch @ ...ommitted...:3r.handle @ ...ommitted...:3
```

**Comment by ravishivt** [comment]
For me, it works with ```1.5.0-beta.0```, but not with ```1.5.0-beta.1```.  I forked the plnkr in the documentation and only changed the Angular src to ```1.5.0-beta.1```, [available here](http://plnkr.co/edit/5p1O9b3q8yRKIb66yGwV?p=preview).  Switch between beta.0 and beta.1 to see it work / not work.  This is the error it generates on beta.1:

```
Error: [ui.select:transcluded] Expected 1 .ui-select-match but got '0'.
    at http://run.plnkr.co/gBd3G34T3oawEWpT/select.js:118:12
    at http://run.plnkr.co/gBd3G34T3oawEWpT/select.js:909:19
    at publicLinkFn (http://ajax.googleapis.com/ajax/libs/angularjs/1.5.0-beta.1/angular.js:7561:29)
    at name.$get.previousCompileContext (http://ajax.googleapis.com/ajax/libs/angularjs/1.5.0-beta.1/angular.js:7900:29)
    at name.$get.boundTranscludeFn (http://ajax.googleapis.com/ajax/libs/angularjs/1.5.0-beta.1/angular.js:7706:16)
    at controllersBoundTransclude (http://ajax.googleapis.com/ajax/libs/angularjs/1.5.0-beta.1/angular.js:8377:18)
    at uis.directive.$timeout.compile (http://run.plnkr.co/gBd3G34T3oawEWpT/select.js:897:9)
    at invokeLinkFn (http://ajax.googleapis.com/ajax/libs/angularjs/1.5.0-beta.1/angular.js:8850:9)
    at nodeLinkFn (http://ajax.googleapis.com/ajax/libs/angularjs/1.5.0-beta.1/angular.js:8350:11)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.5.0-beta.1/angular.js:8580:13 <div class="ui-select-container ui-select-bootstrap dropdown" ng-class="{open: $select.open}" ng-model="address.selected" theme="bootstrap" ng-disabled="disabled" reset-search-input="false" style="width: 300px;">
```

**Comment by NathanWalker** [comment]
That is exactly right @ravishivt ! thanks for clarifying, I'm using 1.5.0-beta.1

**Comment by billforward-alex** [comment]
I was previously specifying for all Angular dependencies in my `bower.json`: `~1.5.0-beta.0`. This produced the described error.

Tightened the bound to `1.5.0-beta.0` and it's working again. :)

**Comment by NathanWalker** [comment]
Any status on making compatible with the `beta.1` since that's the direction the `1.x` series of Angular is taking?

**Comment by scatcher** [comment]
Still doesn't work in beta.2.

**Comment by brboser** [comment]
I have the same issue with beta.2

**Comment by ergomesh** [comment]
I confirm this also doesn't work with the latest beta.2

**Comment by goleafs** [comment]
+1
only thing preventing us from moving to beta 2 :(

**Comment by ergomesh** [comment]
it also does not work with beta.1 but does work with beta.0

**Comment by nickmorton** [comment]
Duplicate thread [see](https://github.com/angular-ui/ui-select/issues/1325)

**Comment by avgalon** [comment]
It does not work with 1.5 release.....do you plan to fix it soon?

**Comment by soichih** [comment]
My app got upgraded to angular 1.5 and ui.select is breaking.. Should I downgrade to Angular 1.4?

**Comment by mrded** [comment]
Angular 1.5.0-rc.2 still not working.

**Comment by harrylog** [comment]
so what ui-select can i use in angular 1.5

**Comment by soichih** [comment]
I've switched from angular-ui-select to just ui-select and it started working for angular 1.5
