### ISSUE TITLE
bower install and support for angular 1.3

### ISSUE THREAD

**Issue by kalyanvgopal** [angular-ui/ui-select#1376]
Hi,

When I do bower install ui-select , I get the following error.
bower ui-select#*             checkout master
TypeError: LRU: key must be a string or number. Almost certainly a bug! undefined
    at typeCheckKey (/usr/local/lib/node_modules/bower/node_modules/lru-cache/lib/lru-cache.js:20:19)
    at LRUCache.get (/usr/local/lib/node_modules/bower/node_modules/lru-cache/lib/lru-cache.js:230:3)
    at /usr/local/lib/node_modules/bower/lib/core/resolvers/GitRemoteResolver.js:122:70
    at _fulfilled (/usr/local/lib/node_modules/bower/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/bower/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:857:14
    at runSingle (/usr/local/lib/node_modules/bower/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/bower/node_modules/q/q.js:125:13)
    at process._tickCallback (node.js:355:11)
bower ui-select#*         invalid-meta angular-ui-select3 is missing "ignore" entry in bower.json

And do you have plans to support 1.3 version of angular?

Regards
Kalyan

**Comment by user378230** [comment]
I don't think ui-select is the correct bower package I think it should be `angular-ui-select` (#779/PR #812) which may or may not work (#1412).
