### ISSUE TITLE
When i upgrade angular version 1.5.0-rc.2  then it is not working

### ISSUE THREAD

**Issue by arv10singh** [angular-ui/ui-select#1422]
angular.js:13307 Error: [ui.select:transcluded] Expected 1 .ui-select-match but got '0'.
    at http://test.com:9012/library/ui-select/dist/select.js:125:12
    at http://test.com:9012/library/ui-select/dist/select.js:1035:19
    at publicLinkFn (http://test.com:9012/bower_components/angular/angular.js:8193:29)
    at http://test.com:9012/bower_components/angular/angular.js:8535:29
    at boundTranscludeFn (http://test.com:9012/bower_components/angular/angular.js:8332:16)
    at controllersBoundTransclude (http://test.com:9012/bower_components/angular/angular.js:9108:20)
    at http://test.com:9012/library/ui-select/dist/select.js:1023:9
    at invokeLinkFn (http://test.com:9012/bower_components/angular/angular.js:9580:9)
    at nodeLinkFn (http://test.com:9012/bower_components/angular/angular.js:9066:11)

**Comment by user378230** [comment]
Please search before creating new issues. Duplicate #1325 

Possible workaround: https://github.com/angular-ui/ui-select/issues/1325#issuecomment-160922087
