### ISSUE TITLE
there is a error when I use ui-select with angular #1.5.0

### ISSUE THREAD

**Issue by Just-Rookie** [angular-ui/ui-select#1474]
When I use angular #1.4.9, everything is ok. But there will be a error when I update angular  to  #1.5.0.

Here is the detail of the error.

Error: [ui.select:transcluded] http://errors.angularjs.org/1.5.0/ui.select/transcluded?p0=Expected%201%20.ui-select-match%20but%20got%20'%7B0%7D'.&p1=0
    at http://localhost:9000/assets/bower_components/ui-select/dist/select.min.js:7:2272
    at http://localhost:9000/assets/bower_components/ui-select/dist/select.min.js:7:15301
    at http://localhost:9000/assets/bower_components/angular/angular.min.js:57:269
    at http://localhost:9000/assets/bower_components/angular/angular.min.js:62:139
    at S.d (http://localhost:9000/assets/bower_components/angular/angular.min.js:59:119)
    at k (http://localhost:9000/assets/bower_components/angular/angular.min.js:64:313)
    at http://localhost:9000/assets/bower_components/ui-select/dist/select.min.js:7:15112
    at ka (http://localhost:9000/assets/bower_components/angular/angular.min.js:79:16)
    at u (http://localhost:9000/assets/bower_components/angular/angular.min.js:66:326)
    at http://localhost:9000/assets/bower_components/angular/angular.min.js:74:460 ``<div class="ui-select-container ui-select-multiple ui-select-bootstrap dropdown form-control" ng-class="{open: $select.open}" tagging="" tagging-label="(new)" ng-model="article.keywords" theme="bootstrap" sortable="true" ng-disabled="disabled">``

**Comment by user378230** [comment]
Please search before creating new issues. 

Duplicates: [#1444](https://github.com/angular-ui/ui-select/issues/1444#issuecomment-185953448) #1422 #1239 [#224](https://github.com/angular-ui/ui-select/issues/224#issuecomment-190081559)

**Comment by Just-Rookie** [comment]
Thanks, I have found the solution proposed  by @llafuente .
