### ISSUE TITLE
Mistake when open the select

### ISSUE THREAD

**Issue by carlosCeron** [angular-ui/ui-select#172]
Hi Guys 

Project with Yeoman,  and the structure has a  views, and controller and i use routeProvider, no use demo.js because each view has a controller.

i follow this steps

/**************************************************************/
bower install angular-ui-select
Inside your HTML add
select.js: <script src="bower_components/angular-ui-select/dist/select.min.js"></script>
select.css: <link rel="stylesheet" href="bower_components/angular-ui-select/dist/select.min.css">
Add the ui.select module as a dependency: angular.module("myApp", ["ui.select"]);

/**************************************************************/
 but when try to open the view give me a error like this

undefined it's no a function, if the steps are this what more need to put on the app.js file.

Log Error

TypeError: undefined is not a function
    at link (http://localhost:9000/bower_components/angular-ui-select/dist/select.js:633:11)
    at nodeLinkFn (http://localhost:9000/bower_components/angular/angular.js:6579:13)
    at compositeLinkFn (http://localhost:9000/bower_components/angular/angular.js:5986:15)
    at nodeLinkFn (http://localhost:9000/bower_components/angular/angular.js:6573:24)
    at compositeLinkFn (http://localhost:9000/bower_components/angular/angular.js:5986:15)
    at publicLinkFn (http://localhost:9000/bower_components/angular/angular.js:5891:30)
    at boundTranscludeFn (http://localhost:9000/bower_components/angular/angular.js:6005:21)
    at controllersBoundTransclude (http://localhost:9000/bower_components/angular/angular.js:6600:18)
    at ngRepeatAction (http://localhost:9000/bower_components/angular/angular.js:20084:15)
    at Object.$watchCollectionAction [as fn] (http://localhost:9000/bower_components/angular/angular.js:12126:13) <div class="select2-result-label ui-select-choices-row-inner" uis-transclude-append="">

i try this issue https://github.com/angular-ui/ui-select/issues/96 but the error it's the same, change the files select.min.js and select.min.css => select.js and select.css but the error it's the same

**Comment by user378230** [comment]
Closing this issue as over a year old and doesn't have a repro sample. 

If you believe its still relevant please reopen with a plunkr (or similar) against the latest version of ui-select (currently v0.15.0)
