### ISSUE TITLE
Some times i have error  [ui.select:transcluded] Expected 1 .ui-select-choices but got '0'.

### ISSUE THREAD

**Issue by a-reznic** [angular-ui/ui-select#218]
Error: [ui.select:transcluded] Expected 1 .ui-select-choices but got '0'.
    at http://localhost:63342/test/src/js/select.js:77:14
    at http://localhost:63342/test/src/js/select.js:804:19
    at publicLinkFn (http://localhost:63342/test/src/js/libs/angular.js:5933:29)
    at boundTranscludeFn (http://localhost:63342/test/src/js/libs/angular.js:6059:21)
    at controllersBoundTransclude (http://localhost:63342/test/src/js/libs/angular.js:6669:18)
    at link (http://localhost:63342/test/src/js/select.js:786:9)
    at nodeLinkFn (http://localhost:63342/test/src/js/libs/angular.js:6648:13)
    at http://localhost:63342/test/src/js/libs/angular.js:6850:13
    at http://localhost:63342/test/src/js/libs/angular.js:8050:11
    at wrappedCallback (http://localhost:63342/test/src/js/libs/angular.js:11498:81) <div class="ui-select-bootstrap dropdown ng-pristine ng-valid" ng-class="{open: $select.open}" ng-model="roomCtrl.tab.regionId" theme="bootstrap" on-select="roomCtrl.roomSelectChangedRegion($item)"> 

if refresh page error disapear and sometime error appear...

**Comment by nasturah** [comment]
I was struggling to resolve this issue for 2 days. I tried different versions of Angular (1.2.9, 1.3.13, and 1.4.0b), choice of theme, timeouts etc. - nothing worked.

I finally resolved the issue by copying the theme templates to be in-line angular script tags instead of loading them via an HTTP request. There was a strange race condition between compilation of the templates and transclusion of the drop-down items - this was the only thing that was able to fix the problem.

This also fixes issue [https://github.com/angular-ui/ui-select/issues/224] with the .ui-select-match transclusion.

You also need to make sure that the templates are in the following order:
match, choices, select

```javascript
<script type="text/ng-template" id="selectize/match.tpl.html">
    <div ng-hide="($select.open || $select.isEmpty())" class="ui-select-match" ng-transclude></div>
</script>

<script type="text/ng-template" id="selectize/choices.tpl.html">
    <div ng-show="$select.open" class="ui-select-choices selectize-dropdown single">
        <div class="ui-select-choices-content selectize-dropdown-content">
            <div class="ui-select-choices-group optgroup" role="listbox">
                <div ng-show="$select.isGrouped" class="ui-select-choices-group-label optgroup-header"
                     ng-bind="$group.name"></div>
                <div role="option" class="ui-select-choices-row"
                     ng-class="{active: $select.isActive(this), disabled: $select.isDisabled(this)}">
                    <div class="option ui-select-choices-row-inner" data-selectable></div>
                </div>
            </div>
        </div>
    </div>
</script>

<script type="text/ng-template" id="selectize/select.tpl.html">
    <div class="ui-select-container selectize-control single" ng-class="{'open': $select.open}">
        <div class="selectize-input"
             ng-class="{'focus': $select.open, 'disabled': $select.disabled, 'selectize-focus' : $select.focus}"
             ng-click="$select.activate()">
            <div class="ui-select-match"></div>
            <input type="text" autocomplete="off" tabindex="-1"
                   class="ui-select-search ui-select-toggle"
                   ng-click="$select.toggle($event)"
                   placeholder="{{$select.placeholder}}"
                   ng-model="$select.search"
                   ng-hide="!$select.searchEnabled || ($select.selected && !$select.open)"
                   ng-disabled="$select.disabled"
                   aria-label="{{$select.baseTitle}}">
        </div>
        <div class="ui-select-choices"></div>
    </div>
</script>
```

**Comment by martinoss** [comment]
@nasturah thanks, this is the only functioning workaround for me so far.

**Comment by audreyn** [comment]
I applied the fix mentionned here: #1325, but I still get the error: `Error: [ui.select:choices] Expected multiple .ui-select-choices-row but got '0'.` when I select an item on list. I think this is because in my template I use the `group-by` attribute. Does someone has the same issue ?

**Comment by chuckyblack** [comment]
@audreyn  Yes, I have the same issue. It occurs only with **group-by** attribute.

**Comment by MacGyver27** [comment]
`Error: [ui.select:choices] Expected multiple .ui-select-choices-row but got '0'.`
+1 (0.14.9, Angular 1.5.0)

@chuckyblack it does not.. I have it without `group-by` just using multiple and error gets generated insanely many times..

Also feeling up the choices feels extremely laggy compared to 0.13.2 and Angular 1.4.8.. It does not allow me to select/scroll until list is fully loaded.. which takes up to 3s for about 200 items.

```
<ui-select multiple ng-model="maintenance.devices">
    <ui-select-match class="ui-select-match" placeholder="select device...">
        {{$item.hostname}} ({{$item.ip}})
    </ui-select-match>
    <ui-select-choices class="ui-select-choices" repeat="ne in networkElements | filter: $select.search">
        <div ng-bind-html="ne.hostname | highlight: $select.search"></div>
        <div ng-bind-html="ne.ip | highlight: $select.search"></div>
    </ui-select-choices>
</ui-select>
```

Any solution at the moment? I applied those classes which did not solve the issue, just decreased the probability of the error..

Thanks, Michal

**Comment by realavaloro** [comment]
I am also getting a `Error: [ui.select:choices] Expected multiple .ui-select-choices-row but got '0'.` and feeling  the select ui slower with 0.14.9 and Angular 1.5.0 than before.
This error seems to happen randomly though..

**Comment by curtismorte** [comment]
@realavaloro,
I ran into a very similar problem when I was trying to focus a ui-select as it became visible within the view (modal). Based [on this comment](https://github.com/angular-ui/ui-select/issues/201#issuecomment-66700601), I was using the following code:
`// get the ui select controller
var uiSelect = angular.element("#fooBar").controller('uiSelect');
// Open the select and focus:
uiSelect.activate();`

Mistakenly, I forgot to add the focusser to the select before activating it. Which it turn was causing some of my issues with the dropdown being open before it's proper "user based" trigger sequence.

`// focus the focusser, putting focus onto select but without opening the dropdown
uiSelect.focusser[0].focus();`

Not sure if that helps, but something to consider.

**Comment by wesleycho** [comment]
Should note, that hack is not possible if you are using $compileProvider.debugInfoEnabled(false) for production builds.

This needs a Plunker reproduction though.

**Comment by glorko** [comment]
For me this problem started when I have included ngAnimate into my module

**Comment by ganqqwerty** [comment]
tried workaround, still have this problem in ui-select-choises without group by.

**Comment by maksad** [comment]
+1 same here

**Comment by user378230** [comment]
Please include your angular and ui select library versions if you're going to leave +1s... 

Note only the latest version is supported and this issue still lacks a plunkr.

**Comment by aks0020** [comment]
I have made one sample working plunker using bootstrap modal(with angular 1.5.8, jQuery 3.1.0 bootstrap 3.3.7, ui-bootstrap 2.0.1, latest ui-select), those who are facing similar issue can try to regenerate issue in this.
https://plnkr.co/edit/K7XaKz?p=preview

**Comment by estundidher** [comment]
FROM:
<i class=\"caret pull-right\" ng-click=\"$select.toggle($event)\"></i>

TO:
<i class=\"caret pull-right\"></i>

**Comment by estundidher** [comment]
FROM:
`<i class=\"caret pull-right\" ng-click=\"$select.toggle($event)\"></i>`
TO:
`<i class=\"caret pull-right\"></i>`

This will resolve the issue when clicking on the ui-select arrow

**Comment by julien-vu** [comment]
The issue is still present in the 0.19.4 version

Angular 1.5.8
Angular Bootstrap : 2.1.2

**Comment by lizschwab** [comment]
Having this issue with ui-select version 0.11.2 after upgrading from AngularJS 1.4.8 to 1.5.8. Bootstrap version is 3.3.6.

**Comment by manveer19188** [comment]
Getting error "Error: [ui.select:transcluded] Expected 1 .ui-select-match but got '0'." with ui-select version 0.14.1 as using with Angular 1.6.1.

**Comment by manveer19188** [comment]
Finally resolved by adding the class **ui-select-match** and **ui-select-choices** to **<ui-select-match>** and **<ui-select-choices>** tags respectively.

**Comment by Jakobovski** [comment]
My error was caused by a validation directive on the form, once the validation directive was removed everything worked.

**Comment by exit99** [comment]
I still receive this error on 0.19.6 using kibana 6.2.3's filter_field_select.js file.  Works if I remove the groupby
