### ISSUE TITLE
Keeps throwing error Expected 1 .ui-select-match but got '0'

### ISSUE THREAD

**Issue by martyphee** [angular-ui/ui-select#71]
This is being used in a modal popup.  I've seen it before, but can't remember how I fixed it.  Not sure if it has something to do with the modal or using controlerAs syntax.

http://plnkr.co/edit/UyuPozU95DzvjbOcl8YJ?p=info

``` javascript
 function StudentPollSettingsCtrl($scope, $modalInstance, content, EDITOR_OPTIONS, StudentPollService) {
        this.chartObject = {};

        this.chartType = {};
        this.chartTypes = [
            {
                value: "pie",
                name: "Pie"
            },
            {
                value: "column",
                name: "Column"
            }
        ];
```

``` html
<tab heading="Chart" select="settingsCtrl.updateChart()">
            <div class="row">
                <div class="col-xs-12">
                    <div style="display: inline-block; width: 300px; margin-left: 10px">
                        <ui-select ng-model="settingsCtrl.chartType"
                                   theme="selectize" ng-change="settingsCtrl.updateChart()">
                            <match placeholder="Choose Chart Type">{{$select.selected.name}}</match>
                            <choices repeat="option in settingsCtrl.chartTypes">
                                <div ng-bind-html="option.name"></div>
                            </choices>
                        </ui-select>
                    </div>
                </div>
            </div>
```

``` javascript
Error: [ui.select:transcluded] Expected 1 .ui-select-match but got '0'.
    at http://0.0.0.0:9000/bower_components/angular-ui-select/dist/select.js:32:12
    at http://0.0.0.0:9000/bower_components/angular-ui-select/dist/select.js:360:17
    at publicLinkFn (http://0.0.0.0:9000/bower_components/angular/angular.js:5890:29)
    at boundTranscludeFn (http://0.0.0.0:9000/bower_components/angular/angular.js:6005:21)
    at controllersBoundTransclude (http://0.0.0.0:9000/bower_components/angular/angular.js:6600:18)
    at link (http://0.0.0.0:9000/bower_components/angular-ui-select/dist/select.js:350:7)
    at nodeLinkFn (http://0.0.0.0:9000/bower_components/angular/angular.js:6579:13)
    at delayedNodeLinkFn (http://0.0.0.0:9000/bower_components/angular/angular.js:6798:11)
    at compositeLinkFn (http://0.0.0.0:9000/bower_components/angular/angular.js:5982:15)
    at compositeLinkFn (http://0.0.0.0:9000/bower_components/angular/angular.js:5989:13) <div class="selectize-control single ng-pristine ng-valid" ng-model="settingsCtrl.chartType.selected" theme="selectize" ng-change="settingsCtrl.updateChart()"> 
```

**Comment by scottlepp** [comment]
error is back with angular 1.5

**Comment by codeuniquely** [comment]
went to the link provided  http://plnkr.co/edit/FBjraF?p=preview

and got this console error ...

```
Error: [ui.select:transcluded] Expected 1 .ui-select-match but got '0'.
    at http://run.plnkr.co/Jyc6GTSneCcrkZAF/select.js:32:12
    at http://run.plnkr.co/Jyc6GTSneCcrkZAF/select.js:360:17
    at publicLinkFn (http://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.js:8105:29)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.js:8447:29
    at boundTranscludeFn (http://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.js:8244:16)
    at controllersBoundTransclude (http://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.js:9020:20)
    at link (http://run.plnkr.co/Jyc6GTSneCcrkZAF/select.js:350:7)
    at invokeLinkFn (http://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.js:9492:9)
    at nodeLinkFn (http://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.js:8978:11)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.js:9231:13 <div class="selectize-control single ng-pristine ng-untouched ng-valid ng-scope" ng-model="settingsCtrl.chartType" theme="selectize" ng-change="settingsCtrl.updateChart()">

**Comment by Silur** [comment]
error is back with new syntax 'ui-select-match'

**Comment by manveer19188** [comment]
Getting same error "Error: [ui.select:transcluded] Expected 1 .ui-select-match but got '0'." with ui-select version 0.14.1 as using with Angular 1.6.1.

**Comment by manveer19188** [comment]
Finally resolved by adding the class ui-select-match and ui-select-choices to 

`<ui-select-match> and <ui-select-choices>`

 tags respectively.
