### ISSUE TITLE
When open the option in the select, get the following error for each option, only happens in IE, I am using version 11.

### ISSUE THREAD

**Issue by hummorsa** [angular-ui/ui-select#892]
Error: Invalid argument.
   at Anonymous function (http://localhost:9000/trecs-web/scripts/libraries/angular-1.3.15/angular.min.js:67:309)
   at Anonymous function (http://localhost:9000/trecs-web/scripts/libraries/angular-1.3.15/angular.min.js:89:324)
   at c (http://localhost:9000/trecs-web/scripts/libraries/angular-1.3.15/angular.min.js:120:298)
   at n.prototype.$eval (http://localhost:9000/trecs-web/scripts/libraries/angular-1.3.15/angular.min.js:126:4)
   at n.prototype.$digest (http://localhost:9000/trecs-web/scripts/libraries/angular-1.3.15/angular.min.js:123:98)
   at n.prototype.$apply (http://localhost:9000/trecs-web/scripts/libraries/angular-1.3.15/angular.min.js:126:291)
   at Anonymous function (http://localhost:9000/trecs-web/scripts/libraries/angular-1.3.15/angular.min.js:216:124)
   at n.event.dispatch (http://localhost:9000/trecs-web/scripts/libraries/jquery-2.1.3/jquery.min.js:3:6388)
   at r.handle (http://localhost:9000/trecs-web/scripts/libraries/jquery-2.1.3/jquery.min.js:3:3154)

**Comment by wesleycho** [comment]
Can you create a reproduction in Plunker based on the latest release?
